### PR TITLE
Correctly modify with NULL values

### LINKED ISSUE #655: modify_depth fails when higher levels have NULLs
Hi,
`modify_depth` fails when higher levels have a mix of NULLs and non-NULLs e.g.
```r
> aa <- list(a = NULL, b = list(b1 = NULL, b2 = "hello"))
> aa
$a
NULL

$b
$b$b1
NULL

$b$b2
[1] "hello"


> modify_depth(aa, 
+              .depth = 2,
+              is.character,
+              .ragged = TRUE
+              )
Error in .x[[i]] : subscript out of bounds
```
I would expect
```r
$a
NULL

$b
$b$b1
NULL

$b$b2
[1] "TRUE"
```

Works when the first level has no NULLs
```r
> aa <- list(a = "hi", b = list(b1 = NULL, b2 = "hello"))
> aa
$a
[1] "hi"

$b
$b$b1
NULL

$b$b2
[1] "hello"


> modify_depth(aa, 
+              .depth = 2,
+              is.character,
+              .ragged = TRUE
+              )
$a
[1] "TRUE"

$b
$b$b1
[1] FALSE

$b$b2
[1] TRUE
```
And btw why is the upper level type-stable, and not the lower level ?

And why is it the same when `.ragged = FALSE` ?
```r
> modify_depth(aa, 
+              .depth = 2,
+              is.character
+              )
$a
[1] "TRUE"

$b
$b$b1
[1] FALSE

$b$b2
[1] TRUE
```

Thanks!

### LINKED ISSUE #746: modify_if() can't change a list element to NULL
I can't find a way to set certain list elements to `NULL` with `modify_if()`. Any approach I've tried either removes the elements (which seems weird, because I thought `modify_*()` was size-stable) or creates an extra layer of list-nesting. This may be related to some other issues around pluck-y assignment and modify, such as #636, #634.

``` r
library(purrr)

(x <- list("a", "b"))
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"

(x_I_want <- list("a", NULL))
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> NULL

modify_if(x, ~.x == "b", NULL)
#> Error: Can't convert NULL to function
#> Backtrace:
#>     █
#>  1. ├─purrr::modify_if(x, ~.x == "b", NULL)
#>  2. └─purrr:::modify_if.default(x, ~.x == "b", NULL)
#>  3.   ├─purrr::as_mapper(.f, ...)
#>  4.   └─purrr:::as_mapper.default(.f, ...)
#>  5.     └─rlang::as_function(.f)
#>  6.       └─rlang:::abort_coercion(x, friendly_type("function"))

modify_if(x, ~.x == "b", ~ NULL)
#> [[1]]
#> [1] "a"

modify_if(x, ~.x == "b", ~ list(NULL))
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [[2]][[1]]
#> NULL

modify_if(x, ~.x == "b", function(z) NULL)
#> [[1]]
#> [1] "a"

modify_if(x, ~.x == "b", function(z) list(NULL))
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [[2]][[1]]
#> NULL
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

### LINKED ISSUE #753: `modify` fails when `.f` returns NULL
`purrr::modify.default` should check explicitly for null values

``` r

X <- list(a = 1, b = NULL, c = 3)
purrr:::modify(X, identity)
#> Error in .x[[i]]: subscript out of bounds
```

<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Likely duplicates #655 and #746. Creating the new issue with simple reprex to create a sense of urgency :) If a simple check for NULL in modify.default is ok with you I can create a PR and add tests.

### PR DESCRIPTION
**Pull request by hadley**
Fixes #655. Fixes #746. Fixes #753. Closes #754.

`list_assign()` from @DavisVaughan. Tests from @vspinu. I chose not to worry about the data frame case, as the existing error is ok.

### CODE REVIEW

File: R/modify.R [hunk 1]
```diff
@@ -473,3 +473,12 @@ inv_which <- function(x, sel) {
     stop("unrecognised index type", call. = FALSE)
   }
 }
+
+`list_assign2<-` <- function(x, i, value) {
```
Comment (lionel-) [inline R/modify.R:477]: Interesting, I have never seen an assigner function like this before. Should it be called `list_assigner2()`, i.e. a noun? With a verb I think I'm expecting a UI like `vec_assign()`.

Comment (lionel-) [reply R/modify.R:477]: oh it should probably be `list_slice2<-` actually?

**Review by lionel- — APPROVED** [review]

File: R/modify.R (hunk 1 above)
Comment (hadley) [reply R/modify.R:477]: Oh yeah, duh.
