### PR TITLE
Test naming behaviour for combiners

### LINKED ISSUE #997: `list_c()` needs to deal with names
``` r
purrr:::list_c(list(a = 1:2, b = 1:3))
#> Error in `list_unchop()`:
#> ! Can't merge the outer name `a` with a vector of length > 1.
#> Please supply a `.name_spec` specification.

#> Backtrace:
#>     ▆
#>  1. ├─purrr:::list_c(list(a = 1:2, b = 1:3))
#>  2. │ └─vctrs::list_unchop(x, ptype = ptype, error_call = current_env())
#>  3. └─rlang::abort(message = message)
```

<sup>Created on 2022-11-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by hadley**
Fixes #997

### CODE REVIEW

File: R/list-combine.R [hunk 1]
```diff
@@ -40,7 +40,17 @@
 list_c <- function(x, ..., ptype = NULL) {
   vec_check_list(x)
   check_dots_empty()
-  list_unchop(x, ptype = ptype, error_call = current_env())
+
+  # TODO: Ideally we'd set `name_spec = zap()` to drop names from both `args`
+  # and its elements for performance, but that doesn't work for non-vctrs types.
+  # https://github.com/r-lib/vctrs/issues/1106
```
Comment (DavisVaughan) [inline R/list-combine.R:46]: LOL

Comment (DavisVaughan) [inline R/list-combine.R:46]:
```suggestion
  # For `list_c()`, we don't expose `list_unchop()`'s `name_spec` arg,
  # and instead strip outer names to avoid collisions with inner names
```

Comment (DavisVaughan) [reply R/list-combine.R:46]: I don't think the message is exactly the same, because we don't want to zap _all_ the names, just the outer ones

File: tests/testthat/test-list-combine.R [hunk 2]
```diff
@@ -13,6 +13,11 @@ test_that("list_c() can enforce ptype", {
   )
 })
 
+test_that("list_c() strips outer names and preserves inner names", {
```
Comment (DavisVaughan) [inline tests/testthat/test-list-combine.R:16]:
```suggestion
test_that("list_c() strips outer names and preserves inner names (#997)", {
```

**Review by DavisVaughan — APPROVED** [review]

File: tests/testthat/test-list-combine.R [hunk 3]
```diff
@@ -38,6 +43,10 @@ test_that("list_rbind() row-binds compatible data.frames", {
 
   expect_equal(list_rbind(list(df1, df2)), data.frame(x = 1:2, y = c(NA, 1)))
 
+  # and names don't make a difference
```
Comment (DavisVaughan) [inline tests/testthat/test-list-combine.R:46]:
```suggestion
  # and names don't make a difference unless `names_to` is set
```
