### PR TITLE
Fix `prepend()` with empty list

### LINKED ISSUE #637: prepend: fails for empty list
`purrr::prepend` fails for empty list due to the checking of the `before` param though (partly based on the documentation) I would expect it to work as `base::append` by default. Is there a reason for this?

If you agree that it should work for empty lists as well I am happy to submit a PR.

``` r
purrr::prepend(list(), "a")
#> Error in purrr::prepend(list(), "a"): before > 0 && before <= n is not TRUE

append("a", list())
#> [[1]]
#> [1] "a"

purrr::prepend(list("b"), "a")
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"
append("a", list("b"))
#> [[1]]
#> [1] "a"
#> 
#> [[2]]
#> [1] "b"
```

Created on 2019-02-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

My first idea for implementation:
```
function (x, values, before = 1) 
{
    n <- length(x)
    stopifnot(n == 0 || (before > 0 && before <= n))
    if (before == 1) {
        c(values, x)
    }
    else {
        c(x[1:(before - 1)], values, x[before:n])
    }
}
```

### PR DESCRIPTION
**Pull request by czeildi**
- changes default value for `before` argument from 1 to `NULL`
- behaviour is identical for non-empty list
- by default now appends at the beginning for empty list instead throwing an error
- if before is not NULL, still throws error for empty list
- error message now includes NULL check for all cases

Fixes #637

(I redid a previous pull request with the same content where I did not follow best practices described in https://happygitwithr.com/fork-and-clone.html . Now I am creating a PR from a non-master branch.)

### CODE REVIEW

File: tests/testthat/test-prepend.R [hunk 1]
```diff
@@ -13,3 +13,27 @@ test_that("prepend is clearer version of merging with c()", {
     }
   )
 })
+
+test_that("prepend appends at the beginning for empty list by default", {
+  x <- list()
```
Comment (lionel-) [inline tests/testthat/test-prepend.R]: Nitpick: I would write this as `expect_identical(prepend(list(), 1), 1)` for clarity.

File: tests/testthat/test-prepend.R [hunk 2]
```diff
@@ -13,3 +13,27 @@ test_that("prepend is clearer version of merging with c()", {
...
+  expect_identical(
+    x %>% prepend(1),
+    x %>% c(1, .)
+  )
+})
+
+test_that("prepend throws error if before param is neither NULL nor between 1 and length(x)", {
+  expect_error(
+    prepend(list(), 1, before = 1),
+    "is.null(before) || (before > 0 && before <= n) is not TRUE"
```
Comment (lionel-) [inline tests/testthat/test-prepend.R]: This message testing seems too stringent because the message is generated upstream (by `base::stopifnot()`) and so is not under the control of purrr. Upstream changes are unlikely but would cause these tests to fail.

**Comment by lionel-** [comment]
Thanks!
