### PR TITLE
More support for handling indexed errors

### LINKED ISSUE #1022: Find a solution for the inverted chained error problem
In https://github.com/tidyverse/tidyr/pull/1430 we had an issue where the chained error of `map()` results in a confusing error message.

It seems like any case where we need to pass `error_call` through to `.f` can result in an "inverted" chained error. Really `fn()` is the one calling `map()` here, but it is reported like `map()` called `fn()`, which is quite confusing.

The current hack is to avoid `map()` altogether and switch back to `lapply()`, but that is obviously not great.

We might need something like `with_no_indexed_errors()` that we can wrap the `map()` with to turn off the error chaining. In the tidyr case I don't think we'd ever want to report the index of the failure, and we wouldn't want `map()` mentioned in the error at all.

``` r
library(purrr)
library(rlang)

fn_one <- function(x, error_call = caller_env()) {
  if (x == 3L) {
    abort("Something is wrong.", call = error_call)
  }
  
  x
}

fn <- function(x) {
  error_call <- current_env()
  map(x, \(.x) fn_one(.x, error_call = error_call))
}

fn(1:5)
#> Error in `map()`:
#> ℹ In index: 3.
#> Caused by error in `fn()`:
#> ! Something is wrong.

#> Backtrace:
#>     ▆
#>  1. └─global fn(1:5)
#>  2.   └─purrr::map(x, function(.x) fn_one(.x, error_call = error_call))
#>  3.     └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  4.       ├─purrr:::with_indexed_errors(...)
#>  5.       │ └─base::withCallingHandlers(...)
#>  6.       └─.f(.x[[i]], ...)
#>  7.         └─global fn_one(.x, error_call = error_call)
#>  8.           └─rlang::abort("Something is wrong.", call = error_call)
```

With `lapply()`:

``` r
fn2 <- function(x) {
  error_call <- current_env()
  lapply(x, \(.x) fn_one(.x, error_call = error_call))
}

fn2(1:5)
#> Error in `fn2()`:
#> ! Something is wrong.

#> Backtrace:
#>     ▆
#>  1. └─global fn2(1:5)
#>  2.   └─base::lapply(x, function(.x) fn_one(.x, error_call = error_call))
#>  3.     └─FUN(X[[i]], ...)
#>  4.       └─global fn_one(.x, error_call = error_call)
#>  5.         └─rlang::abort("Something is wrong.", call = error_call)
```

### LINKED ISSUE #1027: `map()` and `pmap()` remove class from error
I noticed this when googledrive had a test failure, where the function in question uses a `tryCatch()`:

https://github.com/tidyverse/googledrive/blob/7e8fa7abcb220566d2e1e99621b6e5d41e8f1c5b/R/shortcut.R#L184-L187

This `resolve_one()` function ultimately gets called inside `pmap()` and as of v1.0.0, the error no longer has the expected class.

---

With purrr 0.3.5, the class of an error thrown by `.f` is preserved. Here it's an `oops_error`.

``` r
f <- function(x) {
  if (x) {
    cli::cli_abort("oops", class = "oops_error")
  }
  x
}
f(FALSE)
#> [1] FALSE
f(TRUE)
#> Error in `f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─global f(TRUE)
#>  2.   └─cli::cli_abort("oops", class = "oops_error")
#>  3.     └─rlang::abort(...)

packageVersion("purrr")
#> [1] '0.3.5'

purrr::map(c(FALSE, TRUE), f)
#> Error in `.f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─purrr::map(c(FALSE, TRUE), f)
#>  2.   └─global .f(.x[[i]], ...)
#>  3.     └─cli::cli_abort("oops", class = "oops_error")
#>  4.       └─rlang::abort(...)
err <- rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
err
#> <error/oops_error>
#> Error in `.f()`:
#> ! oops
#> ---
#> Backtrace:
#>  1. rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
#>  8. purrr::map(c(FALSE, TRUE), f)
#>  9. global .f(.x[[i]], ...)
class(err)
#> [1] "oops_error"  "rlang_error" "error"       "condition"
```

---

But as of v1.0.0, the error no longer has that condition.

``` r
f <- function(x) {
  if (x) {
    cli::cli_abort("oops", class = "oops_error")
  }
  x
}
f(FALSE)
#> [1] FALSE
f(TRUE)
#> Error in `f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─global f(TRUE)
#>  2.   └─cli::cli_abort("oops", class = "oops_error")
#>  3.     └─rlang::abort(...)

packageVersion("purrr")
#> [1] '1.0.0'

purrr::map(c(FALSE, TRUE), f)
#> Error in `purrr::map()`:
#> ℹ In index: 2.
#> Caused by error in `.f()`:
#> ! oops

#> Backtrace:
#>     ▆
#>  1. └─purrr::map(c(FALSE, TRUE), f)
#>  2.   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  3.     ├─purrr:::with_indexed_errors(...)
#>  4.     │ └─base::withCallingHandlers(...)
#>  5.     └─global .f(.x[[i]], ...)
#>  6.       └─cli::cli_abort("oops", class = "oops_error")
#>  7.         └─rlang::abort(...)
err <- rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
err
#> <error/rlang_error>
#> Error in `purrr::map()`:
#> ℹ In index: 2.
#> Caused by error in `.f()`:
#> ! oops
#> ---
#> Backtrace:
#>   1. rlang::catch_cnd(purrr::map(c(FALSE, TRUE), f))
#>   8. purrr::map(c(FALSE, TRUE), f)
#>   9. purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  12. global .f(.x[[i]], ...)
class(err)
#> [1] "rlang_error" "error"       "condition"
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #1022. Fixes #1027.

The text is still pretty rough, but @jennybc hopefully it's enough to solve your problem. I suspect you'll be best off waiting for purrr 1.0.1 which I'll hopefully submit later this week.

### CODE REVIEW

**Comment by mlane3** [comment]
Please don't close both https://github.com/tidyverse/purrr/issues/1022 and https://github.com/tidyverse/purrr/pull/1034

This does not handle Rstudio crashes or operating system crash errors.  When I tested your fix it caused unrecoverable errors for rlang 1.0.6 and a version of vctrs that I am not able to identify.
I got basically this error again: https://studio.youtube.com/video/tz5PIVs6QPQ/edit

I know enough to know about the issue is not with Rstudio or R but windows. 
If you like to do a test, add a check for Windows Server 2016.

**Review by lionel- — COMMENTED** [review]
I like that this solves a lot of problems using only the existing condition system.

For the use case of overriding the error message of indexed errors, rethrowing is a bit heavy handed because of all the extra stuff included in backtraces, but it has the advantage that we don't need to change the interface of `map()`.

For the important use case of simple error-catching however, I think the patterns used here are a bit complicated.

Also we're currently encouraging using `tryCatch()` to rethrow errors which is problematic since it prevents, `recover()`, `traceback()`, and `rlang::global_handle()` from reaching in the nested contexts. At the same time we probably don't want to get into details about `tryCatch()` vs `withCallingHandlers()` here, as that would make the vignette even more complicated?

So I'm thinking we should recommend `try_fetch()` and bake in `cnd_inherits()` semantics. So that you'd just need to do:

```r
try_fetch(
  map(c(1, 4, 2, 5, 3), f),
  my_error = function(err) {
    print("Hello! why am I not being called?")
  }
)
```

And then usage of `map()` is an implementation detail that has no impact on the condition handling code, lowering the maintenance costs.

**Comment by lionel-** [comment]
@mlane3 It looks like there is something wrong in your package library, I recommend reinstalling all the packages from scratch and make sure that you're not using binaries compiled for versions of R older than the one you're using. See `pak::pak()` for a safer way of installing packages on Windows.

In any case the problem you're having is off-topic for this PR and for both of the issues you've linked to. https://community.rstudio.com or Stack Overflow might be better venues to get help about this.

File: R/map.R [hunk 1]
```diff
@@ -65,6 +65,9 @@
 #'
 #' * `walk()` returns the input `.x` (invisibly). This makes it easy to
 #'    use in a pipe. The return value of `.f()` is ignored.
+#'
+#' Any errors thrown by `.f` will be wrapped in an error with class
+#' `purrr_error_indexed`. See `vignette("programming")` for details.
```
[the remark this answers is not in the document]
Comment (mlane3) [reply R/map.R:70]: > Should also include a short summary of the error class invariants.
> 
> I'm thinking the `index` type should be documented as `c("numeric", "character")` even though we currently only use numeric indices?

There are a lot of cases where a non-numeric factor index is needed or a index with leading zeros.  PBkeys and spatial indexes are good examples that the index is never numeric but is ordinal like a factor.  There are still recycling issues.
However, you are correct that purr "now" uses only numeric indexes much to my disappointment.

**Comment by mlane3** [comment]
> @mlane3 It looks like there is something wrong in your package library, I recommend reinstalling all the packages from scratch and make sure that you're not using binaries compiled for versions of R older than the one you're using. See `pak::pak()` for a safer way of installing packages on Windows.
> In any case the problem you're having is off-topic for this PR and for both of the issues you've linked to. https://community.rstudio.com or Stack Overflow might be better venues to get help about this.

@lionel-  Here is what I think the ""topic"" is...
*Purr's map() makes errors confusing with index issues or masks errors from the users so that then they cannot debug or post a github issue.  In this way, it prevents an reproduceable example of the problem.*

So what I have said before is very **on-topic** and toward your point about not being part of this PR. 
Also its really hard to decide what is in a PR when every thread you make is automatically closed after the first or second reply. 
So with all due respect, I think you really need to take time to read everything written before.   Like how this build fails for the Windows Server 2016.  

I really like to know what version of ""Windows"" latest release because I am certain that it fails.  Why? 
Why you might ask?
https://community.rstudio.com/search?q=Windows%20install%20order%3Alatest_topic
Because if you search windows and install in the RStudio community you realize that since 11-03-2022. 
I suspect that you already know this though and you just.

*I will make things clearer, I do not see concrete evidence that this build passes for Windows 11 or any Windows Server*
*I am beginning to question whether or not R-CMD-check process tests on any standard build of latest Windows release because of your instance that it does*

**Comment by mlane3** [comment]
@lionel- and @hadley 

Now, may it loosk ""off-topic"" because I was giving the people in #1027 specific examples for things you had not considered ie. fatal errors.... what happens if purr masks the log of fatal error that would normally cause the R application to crash or crash the OS,  

Errors that when I test with purr should probably be caught prior to installation completion, but cause problems after installation .
I think it might be best for me to show _another example_ of non-fatal errors that I hope are fixed by a proper running purr 1.0.0. I These are all errors that I hope @lionel- finally figure out what is wrong, but I honestly still have to properly verify.  This means I need to get purr 1.0.0 installed on a Window 11 or Windows Server. 

There are over 4083 tidyverse related errors,  the one highlighted are the one currently open related to purr.  I would be more than happy to test one of these on my personal computer. 
![image](https://user-images.githubusercontent.com/1785885/210561782-cdd89a05-dd11-4a6b-8e81-60997a1e8399.png

**Comment by hadley** [comment]
@mlane3 why don't you focus on explaining your problem with `when()`/`gsub()` first. There's no reason why you can't continue to comment in a closed thread and that might help us get to the root of what your problem is.

**Comment by mlane3** [comment]
> @mlane3 why don't you focus on explaining your problem with `when()`/`gsub()` first. There's no reason why you can't continue to comment in a closed thread and that might help us get to the root of what your problem is.

Lets start simple, what version of windows are you build testing on?  Ie. the exact update and full build version number. 

P.S.  The fact that you marked it as off topic makes me even more certain that this build is failing for other versions of Windows.

File: R/map.R [hunk 2]
```diff
@@ -202,8 +205,10 @@ with_indexed_errors <- function(expr, i, error_call = caller_env()) {
       } else {
         cli::cli_abort(
           c(i = "In index: {i}."),
+          index = i,
           parent = cnd,
-          call = error_call
+          call = error_call,
+          class = "purrr_error_indexed"
```
[the remark this answers is not in the document]
Comment (hadley) [reply R/map.R:211]: That seems reasonable to add to rlang, and then when it exists, purrr can use it.

**Comment by hadley** [comment]
@mlane3 that is totally off topic for that issue, which is not at all related to OS versions.

**Comment by hadley** [comment]
@mlane3 none of those concerns are relevant to this PR. Please stop adding comments here or I will have to block you.

File: R/map.R (hunk 1 above)
[the remark this answers is not in the document]
Comment (DavisVaughan) [reply R/map.R:70]: I think it would be nice if `index` was always an integer, and if there is also a character index available then it should go in an additional `name` slot. That is better for type stability when rethrowing errors upstream.

i.e. in tidyr I want to catch the `index` and always report it as the row number of the failure

**Comment by DavisVaughan** [comment]
POC usage in tidyr https://github.com/tidyverse/tidyr/pull/1440

File: vignettes/programming.Rmd [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+---
+
+```{r, include = FALSE}
+knitr::opts_chunk$set(
+  collapse = TRUE,
+  comment = "#>"
+)
+```
+
+This vignette contains some details of using programming with purrr specifically when you're using it from a package.
```
Comment (DavisVaughan) [inline vignettes/programming.Rmd:17]:
```suggestion
This vignette contains some details of programming with purrr specifically when you're using it from a package.
```

File: vignettes/programming.Rmd [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+)
+```
+
+In order to handle the error thrown by `f()`, you'll need to use `rlang::cnd_inherits()` on the parent error:
+
+```{r}
+tryCatch(
+  map(c(1, 4, 2, 5, 3), f),
+  purrr_error_indexed = function(err) {
+    if (rlang::cnd_inherits(err$parent, "my_error")) {
```
Comment (DavisVaughan) [inline vignettes/programming.Rmd:114]: It was interesting to read that you can actually use `cnd_inherits()` directly on `err` and it will check to see if its `$parent` inherits from the error class too

File: vignettes/programming.Rmd [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+
+```{r}
+#| error: true
+tryCatch(
+  map(c(1, 4, 2, 5, 3), f),
+  purrr_error_indexed = function(err) {
+    rlang::cnd_signal(err$parent)
+  }
+)
+```
```
[the remark this answers is not in the document]
Comment (DavisVaughan) [reply vignettes/programming.Rmd:148]: Do we really want to advertise `cnd$call <- call` or `header` overriding? I feel like both are fairly internal details that have a (rather small) chance to change in the future.

**Review by DavisVaughan — APPROVED** [review]
My only gripe left with this is that it is still a little clunky to "turn off" the purrr error wrapping when your `.f` error is "good enough". It was clunky enough that it was cleaner for me to just switch to a for loop in tidyr 

I'm not sure if there is much we can do about that, but I do feel like "just turn it off" is going to be a semi popular request

**Comment by hadley** [comment]
@lionel can you please take another look at the update explanation?

**Review by jennybc — APPROVED** [review]
LGTM

It was a pretty easy and small change to get googledrive working with this:

https://github.com/tidyverse/googledrive/pull/407

File: man/rmd/indexed-error.Rmd [hunk 6]
```diff
@@ -0,0 +1,121 @@
+The `purrr_error_indexed` class is thrown by [map()], [map2()], [pmap()], and friends.
+It wraps errors thrown by applying `.f` to individual elements giving additional information about the location of the error.
```
Comment (lionel-) [inline man/rmd/indexed-error.Rmd:2]: I first read this as "the error is wrapped by applying `.f`".

Something along these lines might be clearer:

"When an error is thrown during the processing of an individual element by the mapped function `.f`, the error gets chained by `map()` and friends to a `purrr_error_indexed` that provides additional information about the location of the error.

File: man/rmd/indexed-error.Rmd [hunk 7]
```diff
@@ -0,0 +1,121 @@
...
+
+# Structure
+
+`purrr_error_indexed` has two fields:
+
+-   `location`: the location of the error as a single integer.
+-   `name`: the name of the location as a string. If the element was not named, `name` will be `NULL`
+
+`purrr_error_indexed` inherits from `rlang_error` which means that it also has a `parent` field which contains the original error thrown by `.f`.
```
Comment (lionel-) [inline man/rmd/indexed-error.Rmd:11]: rlang errors do not necessarily have a `parent` field. (Also technically base errors might contain one if they want to implement the chained error protocol of rlang.). Maybe:

> `purrr_error_indexed` is always constructed as a child error (see the `parent` argument of [rlang::abort()]). It has a `parent` field that contains the original error thrown by `.f`.

File: man/rmd/indexed-error.Rmd [hunk 8]
```diff
@@ -0,0 +1,121 @@
...
+#| error: true
+withCallingHandlers(
+  map(c(1, 4, 2, 5, 3), f),
+  purrr_error_indexed = function(err) {
+    rlang::cnd_signal(err$parent)
+  }
+)
+```
+
+It's important to use `withCallingHandlers()` and not `tryCatch()` here so that `recover()` and other tools will continue to work.
```
Comment (lionel-) [inline man/rmd/indexed-error.Rmd:121]: Because we are resignalling an error, it's important to use `withCallingHandlers()` and not `tryCatch()` in order to we preserve the full backtrace context. This way, `recover()` and other tools will continue to work as expected.
