### PR TITLE
Fix pmap() with empty list on Win32

### LINKED ISSUE #565: pmap_chr() on a 0-column tibble crashes 32-bit R 3.5.1
Using 43c3eb329001152762f618a62beec111702734b9:

```r
purrr::pmap_chr(tibble::tibble(x = 1)[, 0], paste)
```

crash

``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: i386-w64-mingw32/i386 (32-bit)
#> Running under: Windows 7 x64 (build 7601) Service Pack 1
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
#>  [5] tools_3.5.1     htmltools_0.3.6 yaml_2.2.0      Rcpp_0.12.19   
#>  [9] stringi_1.2.4   rmarkdown_1.10  knitr_1.20      stringr_1.3.1  
#> [13] digest_0.6.18   evaluate_0.12
```

### PR DESCRIPTION
**Pull request by lionel-**
Fixes #565.

Enables Appveyor, even though I couldn't produce a crashing test. It crashes locally but not on Appveyor. Still seems safer to test on Appveyor to get the 32 bit checks.

### CODE REVIEW

File: src/map.c [hunk 1]
```diff
@@ -201,7 +201,10 @@ SEXP pmap_impl(SEXP env, SEXP l_name_, SEXP f_name_, SEXP type_) {
   REPROTECT(f_call = Rf_lcons(f, f_call), fi);
 
   SEXP out = PROTECT(call_loop(env, f_call, n, type, m));
-  copy_names(VECTOR_ELT(l_val, 0), out);
+
+  if (Rf_length(l_val)) {
```
Comment (wlandau) [inline src/map.c]: :+1:
